# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertStatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('is_terminal', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_alertstatusitem_code')],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='alerts.alert')),
                ('status', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='alerts.alertstatusitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.alertstatusitem'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "alerts_alertevent" ("content_type_id", "id", "message", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "triggered_at") VALUES (NEW."content_type_id", NEW."id", NEW."message", NEW."object_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status_id", NEW."triggered_at"); RETURN NULL;', hash='737f95933047a3df65ac4fc2a81fb520e1f788aa', operation='INSERT', pgid='pgtrigger_insert_insert_607e3', table='alerts_alert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "alerts_alertevent" ("content_type_id", "id", "message", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "triggered_at") VALUES (NEW."content_type_id", NEW."id", NEW."message", NEW."object_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status_id", NEW."triggered_at"); RETURN NULL;', hash='df68bcb890385d2b882792e2ab2330a1204733e6', operation='UPDATE', pgid='pgtrigger_update_update_953db', table='alerts_alert', when='AFTER')),
        ),
    ]
